# Site settings
title: joey.sabani
email: joey.sabani@gmail.com
description: "a work in progress: join me on my journey into programming"
baseurl: ""
url: "http://axhi.github.io"
twitter_username: sabanimals
github_username:  axhi

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
